import cors from "cors";
import express from "express";
import serveStatic from "serve-static";

import alumnis from "../routes/alumnis.js";
import auth from "../routes/auth.js";
import bugs from "../routes/bugs.js";
import chatToken from "../routes/chatToken.js";
import communities from "../routes/communities.js";
import programmes from "../routes/programmes.js";
import data from "../routes/data.js";
import departments from "../routes/departments.js";
import error from "../middlewares/error.js";
import expoPushNotifications from "../routes/expoPushNotifications.js";
import expoPushTokens from "../routes/expoPushTokens.js";
import explore from "../routes/explore.js";
import feedback from "../routes/feedback.js";
import grao from "../routes/grao.js";
import hashtags from "../routes/hashtags.js";
import issues from "../routes/issues.js";
import mails from "../routes/mails.js";
import projects from "../routes/projects.js";
import pushTokens from "../routes/pushTokens.js";
import reactions from "../routes/reactions.js";
import reports from "../routes/reports.js";
import sparkleFromPDF from "../routes/sparkleFromPDF.js";
import sparklers from "../routes/sparklers.js";
import sparkles from "../routes/sparkles.js";
import users from "../routes/users.js";

export default function (app) {
  app.use(express.json());
  app.use(serveStatic("public", { acceptRanges: false }));
  app.use(cors({ origin: "*" }));
  app.use("/api/alumnis", alumnis);
  app.use("/api/auth", auth);
  app.use("/api/bugs", bugs);
  app.use("/api/programmes", programmes);
  app.use("/api/chatToken", chatToken);
  app.use("/api/communities", communities);
  app.use("/api/data", data);
  app.use("/api/departments", departments);
  app.use("/api/expoPushNotifications", expoPushNotifications);
  app.use("/api/expoPushTokens", expoPushTokens);
  app.use("/api/explore", explore);
  app.use("/api/feedback", feedback);
  app.use("/api/grao", grao);
  app.use("/api/hashtags", hashtags);
  app.use("/api/issues", issues);
  app.use("/api/mails", mails);
  app.use("/api/projects", projects);
  app.use("/api/pushTokens", pushTokens);
  app.use("/api/reactions", reactions);
  app.use("/api/reports", reports);
  app.use("/api/sparkleFromPDF", sparkleFromPDF);
  app.use("/api/sparklers", sparklers);
  app.use("/api/sparkles", sparkles);
  app.use("/api/users", users);
  app.use(error);
}
